#!/usr/bin/env python3
"""
parse_detections.py
Walks the pthoor/detections-ai-kql repository, reads Sentinel-format YAML
files, and emits _data/detections.yml for the Jekyll site.

Run:
  python scripts/parse_detections.py <detections-repo-dir> <output-yml>
"""

import sys
import os
import re
import yaml

PRODUCT_MAP = {
    'MDO': 'Defender for Office 365',
    'MDE': 'Defender for Endpoint',
    'MDI': 'Defender for Identity',
    'MDA': 'Defender for Cloud Apps',
    'Sentinel': 'Microsoft Sentinel',
}


def find_yml_files(root):
    """Recursively yield .yml files under root, skipping hidden dirs."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith('.')]
        for fname in filenames:
            if fname.endswith('.yml') or fname.endswith('.yaml'):
                yield os.path.join(dirpath, fname)


def pascal_to_display(name):
    """Convert PascalCase to display name: InitialAccess -> Initial Access."""
    return re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', name)


def derive_product(filepath, root):
    """Derive product from folder path using PRODUCT_MAP."""
    rel = os.path.relpath(filepath, root)
    parts = rel.replace('\\', '/').split('/')
    for part in parts:
        if part in PRODUCT_MAP:
            return PRODUCT_MAP[part]
    parent = os.path.basename(os.path.dirname(filepath))
    return PRODUCT_MAP.get(parent, parent)


def parse_yml_file(filepath, root):
    """Parse a Sentinel-format YAML file. Returns a dict or None."""
    with open(filepath, encoding='utf-8') as f:
        try:
            data = yaml.safe_load(f)
        except yaml.YAMLError:
            return None

    if not data or not isinstance(data, dict):
        return None

    name = data.get('name', '')
    if not name:
        return None

    slug = re.sub(r'[^a-z0-9]+', '-',
                  os.path.splitext(os.path.basename(filepath))[0].lower()
                  ).strip('-')

    data_sources = []
    for connector in (data.get('requiredDataConnectors') or []):
        for dt in (connector.get('dataTypes') or []):
            if dt not in data_sources:
                data_sources.append(dt)

    tactics = [pascal_to_display(t) for t in (data.get('tactics') or [])]

    return {
        'slug': slug,
        'name': str(name),
        'description': str(data.get('description') or '').strip().strip("'"),
        'product': derive_product(filepath, root),
        'data_sources': data_sources,
        'tactics': tactics,
        'techniques': [str(t) for t in (data.get('relevantTechniques') or [])],
        'tags': [str(t) for t in (data.get('tags') or [])],
        'kind': str(data.get('kind') or 'Scheduled'),
        'query': str(data.get('query') or '').rstrip(),
    }


def main():
    if len(sys.argv) != 3:
        print(f'Usage: {sys.argv[0]} <detections-repo-dir> <output.yml>',
              file=sys.stderr)
        sys.exit(1)

    repo_dir = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.isdir(repo_dir):
        print(f'Error: {repo_dir} is not a directory', file=sys.stderr)
        sys.exit(1)

    detections = []
    for yml_file in sorted(find_yml_files(repo_dir)):
        entry = parse_yml_file(yml_file, repo_dir)
        if entry:
            detections.append(entry)
            print(f'  parsed: {yml_file} -> {entry["slug"]}')

    detections.sort(key=lambda d: d['name'].lower())

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    header = (
        '# Auto-generated by scripts/parse_detections.py - do not edit manually\n'
        '# Source: https://github.com/pthoor/detections-ai-kql\n'
    )
    body = yaml.dump(
        {'detections': detections},
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(body)

    print(f'Wrote {len(detections)} detection(s) to {output_path}')


if __name__ == '__main__':
    main()
