#!/usr/bin/env python3
"""
parse_detections.py
Walks the pthoor/detections-ai-kql repository and emits _data/detections.yml
for the Jekyll site.

Expected KQL file structure (YAML frontmatter + KQL body):

  ---
  title: "Detect Legacy Authentication"
  description: "Detects sign-ins via legacy auth protocols"
  severity: high          # critical | high | medium | low | info
  product: Microsoft Sentinel
  platform: Azure
  tags:
    - identity
    - entra-id
  mitre:
    - T1078               # Valid Accounts
    - TA0001              # Initial Access
  status: stable          # stable | testing | deprecated
  created: 2024-01-15
  ---
  SigninLogs
  | where ...

Run:
  python scripts/parse_detections.py <detections-repo-dir> <output-yml>
"""

import sys
import os
import re
import yaml
from datetime import date


def find_kql_files(root):
    """Recursively yield .kql files under root, skipping hidden dirs."""
    for dirpath, dirnames, filenames in os.walk(root):
        # Skip hidden directories (.git, etc.)
        dirnames[:] = [d for d in dirnames if not d.startswith('.')]
        for fname in filenames:
            if fname.endswith('.kql'):
                yield os.path.join(dirpath, fname)


def parse_kql_file(filepath):
    """Parse a KQL file with optional YAML frontmatter.
    Returns a dict or None on failure."""
    with open(filepath, encoding='utf-8') as f:
        raw = f.read()

    # Split frontmatter from KQL body
    frontmatter = {}
    kql_body = raw.strip()

    if raw.startswith('---'):
        parts = raw.split('---', 2)
        if len(parts) >= 3:
            try:
                frontmatter = yaml.safe_load(parts[1]) or {}
            except yaml.YAMLError:
                frontmatter = {}
            kql_body = parts[2].strip()

    if not kql_body:
        return None

    # Derive slug from file path
    rel = os.path.relpath(filepath)
    slug = re.sub(r'[^a-z0-9]+', '-', os.path.splitext(os.path.basename(filepath))[0].lower()).strip('-')

    # Normalise fields
    severity = str(frontmatter.get('severity', 'info')).lower()
    if severity not in ('critical', 'high', 'medium', 'low', 'info'):
        severity = 'info'

    created = frontmatter.get('created')
    if isinstance(created, date):
        created = created.isoformat()
    else:
        created = str(created) if created else ''

    mitre = frontmatter.get('mitre') or []
    if isinstance(mitre, str):
        mitre = [mitre]

    tags = frontmatter.get('tags') or []
    if isinstance(tags, str):
        tags = [tags]

    return {
        'slug': slug,
        'title': str(frontmatter.get('title') or slug.replace('-', ' ').title()),
        'description': str(frontmatter.get('description') or ''),
        'severity': severity,
        'product': str(frontmatter.get('product') or ''),
        'platform': str(frontmatter.get('platform') or ''),
        'tags': [str(t) for t in tags],
        'mitre': [str(m) for m in mitre],
        'status': str(frontmatter.get('status') or 'stable'),
        'created': created,
        'kql': kql_body,
    }


def main():
    if len(sys.argv) != 3:
        print(f'Usage: {sys.argv[0]} <detections-repo-dir> <output.yml>', file=sys.stderr)
        sys.exit(1)

    repo_dir = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.isdir(repo_dir):
        print(f'Error: {repo_dir} is not a directory', file=sys.stderr)
        sys.exit(1)

    detections = []
    for kql_file in sorted(find_kql_files(repo_dir)):
        entry = parse_kql_file(kql_file)
        if entry:
            detections.append(entry)
            print(f'  parsed: {kql_file} → {entry["slug"]}')

    # Sort: critical first, then high, medium, low, info; then by title
    order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
    detections.sort(key=lambda d: (order.get(d['severity'], 9), d['title'].lower()))

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    header = (
        '# Auto-generated by scripts/parse_detections.py - do not edit manually\n'
        '# Source: https://github.com/pthoor/detections-ai-kql\n'
    )
    body = yaml.dump(
        {'detections': detections},
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(body)

    print(f'Wrote {len(detections)} detection(s) to {output_path}')


if __name__ == '__main__':
    main()
