name: Cleanup bad PR

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  close-pr:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.body, 'by deleting this comment block') || github.event.pull_request.body == ''"
    steps:
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1
        with:
          labels: 'Type: Invalid'
      - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448 # v3
        with:
          # Optional. Post an issue comment just before closing a pull request.
          comment: |
            Thanks for the PR. This is the source repository for https://thoor.tech/.
            For security reasons, I only merge changes after prior discussion. Please open an Issue explaining the change.
      - uses: sudo-bot/action-pull-request-lock@875cc6a949fa9de15563404110fff799d65d4ac9 # v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          lock-reason: spam
